apiVersion: v1
kind: Secret
metadata:
  name: aurora-rds-secret
  namespace: three-tier-app
type: Opaque
stringData:
  # Enter your AWS Aurora PostgreSQL Cluster Endpoint
  DB_HOST: "your-aurora-cluster.cluster-xxxxxx.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "YourAuroraPassword123"
  DB_NAME: "form_db"
  DB_SSL: "true"
