apiVersion: v1
kind: Secret
metadata:
  name: aurora-rds-secret
  namespace: three-tier-app
type: Opaque
stringData:
  # Enter your AWS Aurora PostgreSQL Cluster Endpoint
  DB_HOST: "database-1.cvkyc0o8621q.ap-south-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "Ankit.Mori1626"
  DB_NAME: "postgres"
  DB_SSL: "true"
